name: Lint and Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.6

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v6.1.0
          
    - name: Build
      run: go build -v ./...
